services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DB_NAME:-autoservice_book_db}
      POSTGRES_USER: ${DB_USER:-autoservice_book_db_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=autoservice_book.settings
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    ports:
      - "8000:8000"
    # В режиме разработки можно раскомментировать volume, но он перезапишет /app из образа:
    # - ./your_local_project:/app:cached
    # Если используешь маунт, убедись, что локальная папка содержит тот же пакет (autoservice_book)
    volumes:
      - .:/app:cached

volumes:
  db_data:
